// Code is generated by ucloud-model, DO NOT EDIT IT.

package ufile

import (
	"github.com/ucloud/ucloud-sdk-go/ucloud/request"
	"github.com/ucloud/ucloud-sdk-go/ucloud/response"
)

// GetFuctionAvailableRegionRequest is request schema for GetFuctionAvailableRegion action
type GetFuctionAvailableRegionRequest struct {
	request.CommonBase

	// [公共参数] 项目ID。不填写为默认项目，子帐号必须填写。 请参考[GetProjectList接口](../summary/get_project_list.html)
	// ProjectId *string `required:"false"`

}

// GetFuctionAvailableRegionResponse is response schema for GetFuctionAvailableRegion action
type GetFuctionAvailableRegionResponse struct {
	response.CommonBase

	// 功能可用地域
	FuctionAvailableRegion []FuctionAvailableRegion
}

// NewGetFuctionAvailableRegionRequest will create request of GetFuctionAvailableRegion action.
func (c *UFileClient) NewGetFuctionAvailableRegionRequest() *GetFuctionAvailableRegionRequest {
	req := &GetFuctionAvailableRegionRequest{}

	// setup request with client config
	c.Client.SetupRequest(req)

	// setup retryable with default retry policy (retry for non-create action and common error)
	req.SetRetryable(true)
	return req
}

// GetFuctionAvailableRegion - 获取功能可用地域
func (c *UFileClient) GetFuctionAvailableRegion(req *GetFuctionAvailableRegionRequest) (*GetFuctionAvailableRegionResponse, error) {
	var err error
	var res GetFuctionAvailableRegionResponse

	reqCopier := *req

	err = c.Client.InvokeAction("GetFuctionAvailableRegion", &reqCopier, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}
