// Code is generated by ucloud-model, DO NOT EDIT IT.

package ufile

/*
Mirrors - 回源规则信息

this model is auto created by ucloud code generater for open api,
you can also see https://docs.ucloud.cn/api for detail.
*/
type Mirrors struct {

	// 回源条件
	Condition MirrorCondition

	// 回源规则
	Remote MirrorRemote

	// 回源类型，mirror or redirect
	Type string
}
