// Code is generated by ucloud-model, DO NOT EDIT IT.



package udpn











/*
UDPNData - 
*/
type UDPNData struct {
	
	// 
	Bandwidth int 
	
	// 
	ChargeType string 
	
	// 
	CreateTime int 
	
	// 
	ExpireTime int 
	
	// 
	Peer1 string 
	
	// 
	Peer2 string 
	
	// 
	UDPNId string 
	
}



/*
UDPNLineSet - 
*/
type UDPNLineSet struct {
	
	// 
	BandwidthUpperLimit int 
	
	// 
	LocalRegion string 
	
	// 
	RemoteRegion string 
	
}


