// Code is generated by ucloud-model, DO NOT EDIT IT.

package uhadoop

import (
	"github.com/ucloud/ucloud-sdk-go/ucloud"
	"github.com/ucloud/ucloud-sdk-go/ucloud/auth"
)

// UHadoopClient is the client of UHadoop
type UHadoopClient struct {
	*ucloud.Client
}

// NewClient will return a instance of UHadoopClient
func NewClient(config *ucloud.Config, credential *auth.Credential) *UHadoopClient {
	meta := ucloud.ClientMeta{Product: "UHadoop"}
	client := ucloud.NewClientWithMeta(config, credential, meta)
	return &UHadoopClient{
		client,
	}
}
