// Code is generated by ucloud-model, DO NOT EDIT IT.

package isms

/*
ReceiptPerPhone - 每个目的手机号的发送回执信息
*/
type ReceiptPerPhone struct {

	// 手机号码
	Phone string

	// 回执码
	ReceiptCode string

	// 回执结果描述
	ReceiptDesc string

	// 回执结果(发送成功、发送失败、状态未知)
	ReceiptResult string

	// 回执返回时间
	ReceiptTime int

	// SessionId
	SessionId string
}

/*
ReceiptPerTask - 每个提交任务的视频短信的回执结果集合
*/
type ReceiptPerTask struct {

	// 每个手机号的短信回执信息集合
	ReceiptSet []ReceiptPerPhone

	// 发送短信时返回的TaskId
	TaskId string
}
