// Code is generated by ucloud-model, DO NOT EDIT IT.

package udisk

/*
UDiskSnapshotSet - DescribeUDiskSnapshot

this model is auto created by ucloud code generater for open api,
you can also see https://docs.ucloud.cn/api for detail.
*/
type UDiskSnapshotSet struct {

	// 该快照的cmk id
	CmkId string

	// cmk id 别名
	CmkIdAlias string

	// 该快照cmk的状态, Enabled(正常)，Disabled(失效)，Deleted(删除)，NoCmkId(非加密盘)
	CmkIdStatus string

	// 快照描述
	Comment string

	// 创建时间
	CreateTime int

	// 该快照的密文密钥
	DataKey string

	// 磁盘类型，0:数据盘，1:系统盘
	DiskType int

	// 过期时间
	ExpiredTime int

	// 对应磁盘是否处于可用状态
	IsUDiskAvailable bool

	// 快照名称
	Name string

	// 容量单位GB
	Size int

	// 快照Id
	SnapshotId string

	// 快照状态，Normal:正常,Failed:失败,Creating:制作中
	Status string

	// 快照的源UDisk的Id
	UDiskId string

	// 快照的源UDisk的Name
	UDiskName string

	// 对应磁盘制作快照时所挂载的主机
	UHostId string

	// 是否是加密盘快照，是:"Yes", 否:"No"
	UKmsMode string

	// 快照版本
	Version string
}
