// Code is generated by ucloud-model, DO NOT EDIT IT.

package tests

import (
	"testing"
	"time"

	"github.com/ucloud/ucloud-sdk-go/services/udb"
	"github.com/ucloud/ucloud-sdk-go/ucloud"
	"github.com/ucloud/ucloud-sdk-go/ucloud/utest/driver"
	"github.com/ucloud/ucloud-sdk-go/ucloud/utest/functions"
	"github.com/ucloud/ucloud-sdk-go/ucloud/utest/utils"
	"github.com/ucloud/ucloud-sdk-go/ucloud/utest/validation"
)

func TestScenario3339(t *testing.T) {
	spec.ParallelTest(t, &driver.Scenario{
		PreCheck: func() {
			testAccPreCheck(t)
		},
		Id: "3339",
		Vars: func(scenario *driver.Scenario) map[string]interface{} {
			return map[string]interface{}{
				"DBTypeId":     "mongodb-2.6",
				"InstanceMode": "Normal",
				"InstanceType": "SATA_SSD",
				"Port":         27017,
				"MemoryLimit":  1000,
				"DiskSpace":    20,
				"DBName":       "AUTO-",
				"UseSSD":       "False",
				"GroupName":    "mongodb2.6默认shardsvr配置",
				"Region":       "cn-bj2",
				"Zone":         "cn-bj2-02",
			}
		},
		Owners: []string{"xiangyu.wang@ucloud.cn"},
		Title:  "MongoDB2.6-SSD-副本集-备份管理",
		Steps: []*driver.Step{
			testStep3339CheckUDBInstanceAllowance01,
			testStep3339DescribeUDBParamGroup02,
			testStep3339CreateMongoDBReplicaSet03,
			testStep3339DescribeUDBInstance04,
			testStep3339DescribeUDBInstance05,
			testStep3339DescribeUDBInstance06,
			testStep3339UpdateUDBInstanceBackupStrategy07,
			testStep3339DescribeUDBInstance08,
			testStep3339BackupUDBInstance09,
			testStep3339DescribeUDBBackup10,
			testStep3339DescribeUDBInstanceBackupURL11,
			testStep3339CreateUDBInstance12,
			testStep3339DescribeUDBInstance13,
			testStep3339DeleteUDBBackup14,
			testStep3339StopUDBInstance15,
			testStep3339StopUDBInstance16,
			testStep3339StopUDBInstance17,
			testStep3339StopUDBInstance18,
			testStep3339DeleteUDBInstance19,
			testStep3339DeleteUDBInstance20,
			testStep3339DeleteUDBInstance21,
			testStep3339DeleteUDBInstance22,
		},
	})
}

var testStep3339CheckUDBInstanceAllowance01 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("")
		if err != nil {
			return nil, err
		}
		client := c.(*ucloud.Client)

		req := client.NewGenericRequest()
		_ = req.SetAction("CheckUDBInstanceAllowance")
		err = req.SetPayload(map[string]interface{}{
			"Zone":        step.Scenario.GetVar("Zone"),
			"UseSSD":      "true",
			"SSDType":     "SATA_SSD",
			"Region":      step.Scenario.GetVar("Region"),
			"MemoryLimit": 6000,
			"DiskSpace":   200,
			"Count":       1,
			"ClassType":   "nosql",
		})
		if err != nil {
			return nil, err
		}
		resp, err := client.GenericInvoke(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
		}
	},
	StartupDelay:  time.Duration(0) * time.Second,
	MaxRetries:    0,
	RetryInterval: 0 * time.Second,
	Title:         "核查UDB资源余量",
	FastFail:      false,
}

var testStep3339DescribeUDBParamGroup02 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDescribeUDBParamGroupRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":   step.Scenario.GetVar("Zone"),
			"Region": step.Scenario.GetVar("Region"),
			"Offset": 0,
			"Limit":  100,
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DescribeUDBParamGroup(req)
		if err != nil {
			return resp, err
		}

		step.Scenario.SetVar("DataSet_paramGroup", step.Must(utils.GetValue(resp, "DataSet")))
		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
			validation.Builtins.NewValidator("Action", "DescribeUDBParamGroupResponse", "str_eq"),
		}
	},
	StartupDelay:  time.Duration(5) * time.Second,
	MaxRetries:    0,
	RetryInterval: 0 * time.Second,
	Title:         "获取参数信息",
	FastFail:      false,
}

var testStep3339CreateMongoDBReplicaSet03 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("")
		if err != nil {
			return nil, err
		}
		client := c.(*ucloud.Client)

		req := client.NewGenericRequest()
		_ = req.SetAction("CreateMongoDBReplicaSet")
		err = req.SetPayload(map[string]interface{}{
			"Zone":          step.Scenario.GetVar("Zone"),
			"UseSSD":        "true",
			"Region":        step.Scenario.GetVar("Region"),
			"Quantity":      1,
			"Port":          step.Scenario.GetVar("Port"),
			"ParamGroupId":  step.Must(functions.SearchValue(step.Scenario.GetVar("DataSet_paramGroup"), "GroupName", step.Scenario.GetVar("GroupName"), "GroupId")),
			"Name":          step.Must(functions.Concat(step.Scenario.GetVar("DBName"), step.Scenario.GetVar("DBTypeId"))),
			"MemoryLimit":   step.Scenario.GetVar("MemoryLimit"),
			"InstanceType":  step.Scenario.GetVar("InstanceType"),
			"DiskSpace":     step.Scenario.GetVar("DiskSpace"),
			"DBTypeId":      step.Scenario.GetVar("DBTypeId"),
			"ChargeType":    "Dynamic",
			"AdminPassword": "guanliyuanmima",
		})
		if err != nil {
			return nil, err
		}
		resp, err := client.GenericInvoke(req)
		if err != nil {
			return resp, err
		}

		step.Scenario.SetVar("Primary_id", step.Must(utils.GetValue(resp, "DBIds.0")))
		step.Scenario.SetVar("Secondary_id", step.Must(utils.GetValue(resp, "DBIds.1")))
		step.Scenario.SetVar("Arbiter_id", step.Must(utils.GetValue(resp, "DBIds.2")))
		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
			validation.Builtins.NewValidator("Action", "CreateMongoDBReplicaSetResponse", "str_eq"),
		}
	},
	StartupDelay:  time.Duration(0) * time.Second,
	MaxRetries:    3,
	RetryInterval: 1 * time.Second,
	Title:         "创建DB副本集",
	FastFail:      true,
}

var testStep3339DescribeUDBInstance04 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDescribeUDBInstanceRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":      step.Scenario.GetVar("Zone"),
			"Region":    step.Scenario.GetVar("Region"),
			"Offset":    0,
			"Limit":     100,
			"DBId":      step.Scenario.GetVar("Primary_id"),
			"ClassType": "nosql",
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DescribeUDBInstance(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
			validation.Builtins.NewValidator("Action", "DescribeUDBInstanceResponse", "str_eq"),
			validation.Builtins.NewValidator("DataSet.0.Role", "primary", "str_eq"),
			validation.Builtins.NewValidator("DataSet.0.State", "Running", "str_eq"),
		}
	},
	StartupDelay:  time.Duration(20) * time.Second,
	MaxRetries:    10,
	RetryInterval: 10 * time.Second,
	Title:         "获取云数据库信息",
	FastFail:      false,
}

var testStep3339DescribeUDBInstance05 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDescribeUDBInstanceRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":      step.Scenario.GetVar("Zone"),
			"Region":    step.Scenario.GetVar("Region"),
			"Offset":    0,
			"Limit":     100,
			"DBId":      step.Scenario.GetVar("Secondary_id"),
			"ClassType": "nosql",
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DescribeUDBInstance(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
			validation.Builtins.NewValidator("Action", "DescribeUDBInstanceResponse", "str_eq"),
			validation.Builtins.NewValidator("DataSet.0.Role", "secondary", "str_eq"),
			validation.Builtins.NewValidator("DataSet.0.State", "Running", "str_eq"),
		}
	},
	StartupDelay:  time.Duration(30) * time.Second,
	MaxRetries:    10,
	RetryInterval: 20 * time.Second,
	Title:         "获取云数据库信息",
	FastFail:      false,
}

var testStep3339DescribeUDBInstance06 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDescribeUDBInstanceRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":      step.Scenario.GetVar("Zone"),
			"Region":    step.Scenario.GetVar("Region"),
			"Offset":    0,
			"Limit":     100,
			"DBId":      step.Scenario.GetVar("Arbiter_id"),
			"ClassType": "nosql",
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DescribeUDBInstance(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
			validation.Builtins.NewValidator("Action", "DescribeUDBInstanceResponse", "str_eq"),
			validation.Builtins.NewValidator("DataSet.0.Role", "arbiter", "str_eq"),
			validation.Builtins.NewValidator("DataSet.0.State", "Running", "str_eq"),
		}
	},
	StartupDelay:  time.Duration(10) * time.Second,
	MaxRetries:    10,
	RetryInterval: 20 * time.Second,
	Title:         "获取云数据库信息",
	FastFail:      false,
}

var testStep3339UpdateUDBInstanceBackupStrategy07 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewUpdateUDBInstanceBackupStrategyRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":       step.Scenario.GetVar("Zone"),
			"Region":     step.Scenario.GetVar("Region"),
			"DBId":       step.Scenario.GetVar("Primary_id"),
			"BackupTime": 12,
			"BackupDate": 1111110,
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.UpdateUDBInstanceBackupStrategy(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
		}
	},
	StartupDelay:  time.Duration(20) * time.Second,
	MaxRetries:    3,
	RetryInterval: 1 * time.Second,
	Title:         "修改UDB自动备份策略",
	FastFail:      false,
}

var testStep3339DescribeUDBInstance08 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDescribeUDBInstanceRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":      step.Scenario.GetVar("Zone"),
			"Region":    step.Scenario.GetVar("Region"),
			"Offset":    0,
			"Limit":     100,
			"DBId":      step.Scenario.GetVar("Primary_id"),
			"ClassType": "nosql",
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DescribeUDBInstance(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
			validation.Builtins.NewValidator("Action", "DescribeUDBInstanceResponse", "str_eq"),
			validation.Builtins.NewValidator("DataSet.0.BackupBeginTime", 12, "str_eq"),
			validation.Builtins.NewValidator("DataSet.0.BackupDate", 1111110, "str_eq"),
		}
	},
	StartupDelay:  time.Duration(0) * time.Second,
	MaxRetries:    3,
	RetryInterval: 1 * time.Second,
	Title:         "获取云数据库信息",
	FastFail:      false,
}

var testStep3339BackupUDBInstance09 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewBackupUDBInstanceRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":       step.Scenario.GetVar("Zone"),
			"Region":     step.Scenario.GetVar("Region"),
			"DBId":       step.Scenario.GetVar("Primary_id"),
			"BackupName": "backup-test",
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.BackupUDBInstance(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
		}
	},
	StartupDelay:  time.Duration(0) * time.Second,
	MaxRetries:    3,
	RetryInterval: 300 * time.Second,
	Title:         "备份云数据库",
	FastFail:      false,
}

var testStep3339DescribeUDBBackup10 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDescribeUDBBackupRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":   step.Scenario.GetVar("Zone"),
			"Region": step.Scenario.GetVar("Region"),
			"Offset": 0,
			"Limit":  100,
			"DBId":   step.Scenario.GetVar("Primary_id"),
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DescribeUDBBackup(req)
		if err != nil {
			return resp, err
		}

		step.Scenario.SetVar("BackupId_0", step.Must(utils.GetValue(resp, "DataSet.0.BackupId")))
		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
			validation.Builtins.NewValidator("DataSet.0.State", "Success", "str_eq"),
		}
	},
	StartupDelay:  time.Duration(15) * time.Second,
	MaxRetries:    10,
	RetryInterval: 10 * time.Second,
	Title:         "获取备份列表",
	FastFail:      false,
}

var testStep3339DescribeUDBInstanceBackupURL11 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDescribeUDBInstanceBackupURLRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":     step.Scenario.GetVar("Zone"),
			"Region":   step.Scenario.GetVar("Region"),
			"DBId":     step.Scenario.GetVar("Primary_id"),
			"BackupId": step.Scenario.GetVar("BackupId_0"),
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DescribeUDBInstanceBackupURL(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
			validation.Builtins.NewValidator("BackupPath", "http", "contains"),
			validation.Builtins.NewValidator("InnerBackupPath", "http", "contains"),
		}
	},
	StartupDelay:  time.Duration(10) * time.Second,
	MaxRetries:    0,
	RetryInterval: 0 * time.Second,
	Title:         "获取UDB备份下载地址",
	FastFail:      false,
}

var testStep3339CreateUDBInstance12 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewCreateUDBInstanceRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":          step.Scenario.GetVar("Zone"),
			"Region":        step.Scenario.GetVar("Region"),
			"Quantity":      1,
			"Port":          step.Scenario.GetVar("Port"),
			"ParamGroupId":  step.Must(functions.SearchValue(step.Scenario.GetVar("DataSet_paramGroup"), "GroupName", step.Scenario.GetVar("GroupName"), "GroupId")),
			"Name":          "frombf-mongo30",
			"MemoryLimit":   step.Scenario.GetVar("MemoryLimit"),
			"InstanceType":  step.Scenario.GetVar("InstanceType"),
			"InstanceMode":  "Normal",
			"DiskSpace":     step.Scenario.GetVar("DiskSpace"),
			"DBTypeId":      step.Scenario.GetVar("DBTypeId"),
			"ChargeType":    "Month",
			"BackupId":      step.Scenario.GetVar("BackupId_0"),
			"AdminPassword": "guanliyuanmima",
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.CreateUDBInstance(req)
		if err != nil {
			return resp, err
		}

		step.Scenario.SetVar("frombfDBId", step.Must(utils.GetValue(resp, "DBId")))
		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
		}
	},
	StartupDelay:  time.Duration(10) * time.Second,
	MaxRetries:    3,
	RetryInterval: 1 * time.Second,
	Title:         "创建数据库",
	FastFail:      false,
}

var testStep3339DescribeUDBInstance13 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDescribeUDBInstanceRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":      step.Scenario.GetVar("Zone"),
			"Region":    step.Scenario.GetVar("Region"),
			"Offset":    0,
			"Limit":     100,
			"DBId":      step.Scenario.GetVar("frombfDBId"),
			"ClassType": "nosql",
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DescribeUDBInstance(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
			validation.Builtins.NewValidator("Action", "DescribeUDBInstanceResponse", "str_eq"),
			validation.Builtins.NewValidator("DataSet.0.State", "Running", "str_eq"),
		}
	},
	StartupDelay:  time.Duration(20) * time.Second,
	MaxRetries:    10,
	RetryInterval: 10 * time.Second,
	Title:         "获取云数据库信息",
	FastFail:      false,
}

var testStep3339DeleteUDBBackup14 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDeleteUDBBackupRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":     step.Scenario.GetVar("Zone"),
			"Region":   step.Scenario.GetVar("Region"),
			"BackupId": step.Scenario.GetVar("BackupId_0"),
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DeleteUDBBackup(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
		}
	},
	StartupDelay:  time.Duration(0) * time.Second,
	MaxRetries:    3,
	RetryInterval: 1 * time.Second,
	Title:         "删除备份",
	FastFail:      false,
}

var testStep3339StopUDBInstance15 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewStopUDBInstanceRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":   step.Scenario.GetVar("Zone"),
			"Region": step.Scenario.GetVar("Region"),
			"DBId":   step.Scenario.GetVar("Primary_id"),
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.StopUDBInstance(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
			validation.Builtins.NewValidator("Action", "StopUDBInstanceResponse", "str_eq"),
		}
	},
	StartupDelay:  time.Duration(0) * time.Second,
	MaxRetries:    3,
	RetryInterval: 1 * time.Second,
	Title:         "关闭云数据库",
	FastFail:      false,
}

var testStep3339StopUDBInstance16 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewStopUDBInstanceRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":   step.Scenario.GetVar("Zone"),
			"Region": step.Scenario.GetVar("Region"),
			"DBId":   step.Scenario.GetVar("Secondary_id"),
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.StopUDBInstance(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
			validation.Builtins.NewValidator("Action", "StopUDBInstanceResponse", "str_eq"),
		}
	},
	StartupDelay:  time.Duration(0) * time.Second,
	MaxRetries:    3,
	RetryInterval: 1 * time.Second,
	Title:         "关闭云数据库",
	FastFail:      false,
}

var testStep3339StopUDBInstance17 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewStopUDBInstanceRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":   step.Scenario.GetVar("Zone"),
			"Region": step.Scenario.GetVar("Region"),
			"DBId":   step.Scenario.GetVar("Arbiter_id"),
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.StopUDBInstance(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
			validation.Builtins.NewValidator("Action", "StopUDBInstanceResponse", "str_eq"),
		}
	},
	StartupDelay:  time.Duration(0) * time.Second,
	MaxRetries:    3,
	RetryInterval: 1 * time.Second,
	Title:         "关闭云数据库",
	FastFail:      false,
}

var testStep3339StopUDBInstance18 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewStopUDBInstanceRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":   step.Scenario.GetVar("Zone"),
			"Region": step.Scenario.GetVar("Region"),
			"DBId":   step.Scenario.GetVar("frombfDBId"),
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.StopUDBInstance(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
			validation.Builtins.NewValidator("Action", "StopUDBInstanceResponse", "str_eq"),
		}
	},
	StartupDelay:  time.Duration(0) * time.Second,
	MaxRetries:    3,
	RetryInterval: 1 * time.Second,
	Title:         "关闭云数据库",
	FastFail:      false,
}

var testStep3339DeleteUDBInstance19 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDeleteUDBInstanceRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":   step.Scenario.GetVar("Zone"),
			"Region": step.Scenario.GetVar("Region"),
			"DBId":   step.Scenario.GetVar("frombfDBId"),
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DeleteUDBInstance(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{}
	},
	StartupDelay:  time.Duration(60) * time.Second,
	MaxRetries:    3,
	RetryInterval: 1 * time.Second,
	Title:         "删除云数据库",
	FastFail:      false,
}

var testStep3339DeleteUDBInstance20 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDeleteUDBInstanceRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":   step.Scenario.GetVar("Zone"),
			"Region": step.Scenario.GetVar("Region"),
			"DBId":   step.Scenario.GetVar("Primary_id"),
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DeleteUDBInstance(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{}
	},
	StartupDelay:  time.Duration(0) * time.Second,
	MaxRetries:    3,
	RetryInterval: 1 * time.Second,
	Title:         "删除云数据库",
	FastFail:      false,
}

var testStep3339DeleteUDBInstance21 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDeleteUDBInstanceRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":   step.Scenario.GetVar("Zone"),
			"Region": step.Scenario.GetVar("Region"),
			"DBId":   step.Scenario.GetVar("Secondary_id"),
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DeleteUDBInstance(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{}
	},
	StartupDelay:  time.Duration(0) * time.Second,
	MaxRetries:    3,
	RetryInterval: 1 * time.Second,
	Title:         "删除云数据库",
	FastFail:      false,
}

var testStep3339DeleteUDBInstance22 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDeleteUDBInstanceRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":   step.Scenario.GetVar("Zone"),
			"Region": step.Scenario.GetVar("Region"),
			"DBId":   step.Scenario.GetVar("Arbiter_id"),
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DeleteUDBInstance(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{}
	},
	StartupDelay:  time.Duration(0) * time.Second,
	MaxRetries:    3,
	RetryInterval: 1 * time.Second,
	Title:         "删除云数据库",
	FastFail:      false,
}
