// Code is generated by ucloud-model, DO NOT EDIT IT.

package tests

import (
	"testing"
	"time"

	"github.com/ucloud/ucloud-sdk-go/services/udb"
	"github.com/ucloud/ucloud-sdk-go/ucloud"
	"github.com/ucloud/ucloud-sdk-go/ucloud/utest/driver"
	"github.com/ucloud/ucloud-sdk-go/ucloud/utest/functions"
	"github.com/ucloud/ucloud-sdk-go/ucloud/utest/utils"
	"github.com/ucloud/ucloud-sdk-go/ucloud/utest/validation"
)

func TestScenario491(t *testing.T) {
	spec.ParallelTest(t, &driver.Scenario{
		PreCheck: func() {
			testAccPreCheck(t)
		},
		Id: "491",
		Vars: func(scenario *driver.Scenario) map[string]interface{} {
			return map[string]interface{}{
				"DBTypeId":     "mysql-5.5",
				"InstanceMode": "HA",
				"InstanceType": "SATA_SSD",
				"Port":         3306,
				"MemoryLimit":  1000,
				"DiskSpace":    20,
				"DBName":       "auto_hassd_",
				"UseSSD":       "true",
				"Region":       "cn-bj2",
				"Zone":         "cn-bj2-04",
			}
		},
		Owners: []string{"xiangyu.wang@ucloud.cn"},
		Title:  "Mysql_HA_SSD_mysql 5.5_04",
		Steps: []*driver.Step{
			testStep491DescribeUDBType01,
			testStep491DescribeUDBParamGroup02,
			testStep491DescribeUDBInstancePrice03,
			testStep491CheckUDBInstanceAllowance04,
			testStep491CreateUDBInstance05,
			testStep491DescribeUDBInstance06,
			testStep491DescribeUDBInstanceState07,
			testStep491DescribeUDBInstanceBinlog08,
			testStep491BackupUDBInstanceBinlog09,
			testStep491DescribeUDBLogPackage10,
			testStep491DescribeUDBInstanceBinlogBackupState11,
			testStep491DeleteUDBLogPackage12,
			testStep491BackupUDBInstanceSlowLog13,
			testStep491DescribeUDBLogPackage14,
			testStep491DescribeUDBLogBackupURL15,
			testStep491DescribeUDBInstanceLog16,
			testStep491DeleteUDBLogPackage17,
			testStep491BackupUDBInstanceErrorLog18,
			testStep491DescribeUDBLogPackage19,
			testStep491DescribeUDBBinlogBackupURL20,
			testStep491DescribeUDBInstanceLog21,
			testStep491DeleteUDBLogPackage22,
			testStep491ClearUDBLog23,
			testStep491StopUDBInstance24,
			testStep491DescribeUDBInstance25,
			testStep491DeleteUDBInstance26,
		},
	})
}

var testStep491DescribeUDBType01 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDescribeUDBTypeRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":   step.Scenario.GetVar("Zone"),
			"Region": step.Scenario.GetVar("Region"),
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DescribeUDBType(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
		}
	},
	StartupDelay:  time.Duration(0) * time.Second,
	MaxRetries:    0,
	RetryInterval: 0 * time.Second,
	Title:         "获取云数据库支持类型",
	FastFail:      false,
}

var testStep491DescribeUDBParamGroup02 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDescribeUDBParamGroupRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":   step.Scenario.GetVar("Zone"),
			"Region": step.Scenario.GetVar("Region"),
			"Offset": 0,
			"Limit":  100,
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DescribeUDBParamGroup(req)
		if err != nil {
			return resp, err
		}

		step.Scenario.SetVar("DataSet_paramGroup", step.Must(utils.GetValue(resp, "DataSet")))
		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
		}
	},
	StartupDelay:  time.Duration(0) * time.Second,
	MaxRetries:    0,
	RetryInterval: 0 * time.Second,
	Title:         "获取参数信息",
	FastFail:      false,
}

var testStep491DescribeUDBInstancePrice03 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDescribeUDBInstancePriceRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":        step.Scenario.GetVar("Zone"),
			"Region":      step.Scenario.GetVar("Region"),
			"MemoryLimit": step.Scenario.GetVar("MemoryLimit"),
			"DiskSpace":   step.Scenario.GetVar("DiskSpace"),
			"DBTypeId":    step.Scenario.GetVar("DBTypeId"),
			"Count":       1,
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DescribeUDBInstancePrice(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
		}
	},
	StartupDelay:  time.Duration(0) * time.Second,
	MaxRetries:    0,
	RetryInterval: 0 * time.Second,
	Title:         "获取云数据库价格",
	FastFail:      false,
}

var testStep491CheckUDBInstanceAllowance04 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("")
		if err != nil {
			return nil, err
		}
		client := c.(*ucloud.Client)

		req := client.NewGenericRequest()
		_ = req.SetAction("CheckUDBInstanceAllowance")
		err = req.SetPayload(map[string]interface{}{
			"Zone":        step.Scenario.GetVar("Zone"),
			"UseSSD":      step.Scenario.GetVar("UseSSD"),
			"SSDType":     "SATA",
			"Region":      step.Scenario.GetVar("Region"),
			"MemoryLimit": step.Scenario.GetVar("MemoryLimit"),
			"DiskSpace":   step.Scenario.GetVar("DiskSpace"),
			"Count":       1,
			"ClassType":   "SQL",
		})
		if err != nil {
			return nil, err
		}
		resp, err := client.GenericInvoke(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
		}
	},
	StartupDelay:  time.Duration(0) * time.Second,
	MaxRetries:    0,
	RetryInterval: 0 * time.Second,
	Title:         "核查UDB资源余量",
	FastFail:      false,
}

var testStep491CreateUDBInstance05 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewCreateUDBInstanceRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":          step.Scenario.GetVar("Zone"),
			"Region":        step.Scenario.GetVar("Region"),
			"Quantity":      0,
			"Port":          step.Scenario.GetVar("Port"),
			"ParamGroupId":  step.Must(functions.SearchValue(step.Scenario.GetVar("DataSet_paramGroup"), "DBTypeId", step.Scenario.GetVar("DBTypeId"), "GroupId")),
			"Name":          step.Must(functions.Concat(step.Scenario.GetVar("DBName"), step.Scenario.GetVar("DBTypeId"))),
			"MemoryLimit":   step.Scenario.GetVar("MemoryLimit"),
			"InstanceType":  step.Scenario.GetVar("InstanceType"),
			"InstanceMode":  step.Scenario.GetVar("InstanceMode"),
			"DiskSpace":     step.Scenario.GetVar("DiskSpace"),
			"DBTypeId":      step.Scenario.GetVar("DBTypeId"),
			"ChargeType":    "Month",
			"AdminPassword": "guanliyuanmima",
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.CreateUDBInstance(req)
		if err != nil {
			return resp, err
		}

		step.Scenario.SetVar("DBId", step.Must(utils.GetValue(resp, "DBId")))
		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
		}
	},
	StartupDelay:  time.Duration(1) * time.Second,
	MaxRetries:    3,
	RetryInterval: 1 * time.Second,
	Title:         "创建数据库",
	FastFail:      false,
}

var testStep491DescribeUDBInstance06 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDescribeUDBInstanceRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":      step.Scenario.GetVar("Zone"),
			"Region":    step.Scenario.GetVar("Region"),
			"Offset":    0,
			"Limit":     100,
			"DBId":      step.Scenario.GetVar("DBId"),
			"ClassType": "sql",
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DescribeUDBInstance(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
		}
	},
	StartupDelay:  time.Duration(1) * time.Second,
	MaxRetries:    0,
	RetryInterval: 0 * time.Second,
	Title:         "获取云数据库信息",
	FastFail:      false,
}

var testStep491DescribeUDBInstanceState07 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDescribeUDBInstanceStateRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":   step.Scenario.GetVar("Zone"),
			"Region": step.Scenario.GetVar("Region"),
			"DBId":   step.Scenario.GetVar("DBId"),
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DescribeUDBInstanceState(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
			validation.Builtins.NewValidator("State", "Running", "str_eq"),
		}
	},
	StartupDelay:  time.Duration(30) * time.Second,
	MaxRetries:    50,
	RetryInterval: 10 * time.Second,
	Title:         "获取云数据库状态",
	FastFail:      false,
}

var testStep491DescribeUDBInstanceBinlog08 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDescribeUDBInstanceBinlogRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":      step.Scenario.GetVar("Zone"),
			"Region":    step.Scenario.GetVar("Region"),
			"EndTime":   step.Must(functions.GetTimestamp(10)),
			"DBId":      step.Scenario.GetVar("DBId"),
			"BeginTime": step.Must(functions.Calculate("-", step.Must(functions.GetTimestamp(10)), step.Must(functions.Calculate("*", 86400, 7)))),
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DescribeUDBInstanceBinlog(req)
		if err != nil {
			return resp, err
		}

		step.Scenario.SetVar("DataSet_binlog_01", step.Must(utils.GetValue(resp, "DataSet.0.Name")))
		step.Scenario.SetVar("DataSet_binlog_02", step.Must(utils.GetValue(resp, "DataSet.1.Name")))
		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
		}
	},
	StartupDelay:  time.Duration(10) * time.Second,
	MaxRetries:    0,
	RetryInterval: 0 * time.Second,
	Title:         "获取UDBbinlog列表",
	FastFail:      false,
}

var testStep491BackupUDBInstanceBinlog09 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewBackupUDBInstanceBinlogRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":       step.Scenario.GetVar("Zone"),
			"Region":     step.Scenario.GetVar("Region"),
			"DBId":       step.Scenario.GetVar("DBId"),
			"BackupName": "auto_binlog_package",
			"BackupFile": step.Scenario.GetVar("DataSet_binlog_01"),
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.BackupUDBInstanceBinlog(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
		}
	},
	StartupDelay:  time.Duration(1) * time.Second,
	MaxRetries:    0,
	RetryInterval: 0 * time.Second,
	Title:         "备份UDB指定时间段的binlog列表",
	FastFail:      false,
}

var testStep491DescribeUDBLogPackage10 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDescribeUDBLogPackageRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":   step.Scenario.GetVar("Zone"),
			"Type":   2,
			"Region": step.Scenario.GetVar("Region"),
			"Offset": 0,
			"Limit":  100,
			"DBId":   step.Scenario.GetVar("DBId"),
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DescribeUDBLogPackage(req)
		if err != nil {
			return resp, err
		}

		step.Scenario.SetVar("DataSet_package1", step.Must(utils.GetValue(resp, "DataSet")))
		step.Scenario.SetVar("BackupId", step.Must(utils.GetValue(resp, "DataSet.0.BackupId")))
		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
			validation.Builtins.NewValidator("Action", "DescribeUDBLogPackageResponse", "str_eq"),
			validation.Builtins.NewValidator("DataSet.0.State", "Success", "str_eq"),
		}
	},
	StartupDelay:  time.Duration(150) * time.Second,
	MaxRetries:    20,
	RetryInterval: 10 * time.Second,
	Title:         "列表UDB实例日志备份信息",
	FastFail:      true,
}

var testStep491DescribeUDBInstanceBinlogBackupState11 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDescribeUDBInstanceBinlogBackupStateRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":     step.Scenario.GetVar("Zone"),
			"Region":   step.Scenario.GetVar("Region"),
			"BackupId": step.Scenario.GetVar("BackupId"),
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DescribeUDBInstanceBinlogBackupState(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
			validation.Builtins.NewValidator("Action", "DescribeUDBInstanceBinlogBackupStateResponse", "str_eq"),
		}
	},
	StartupDelay:  time.Duration(5) * time.Second,
	MaxRetries:    3,
	RetryInterval: 1 * time.Second,
	Title:         "获取udb实例备份状态",
	FastFail:      false,
}

var testStep491DeleteUDBLogPackage12 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDeleteUDBLogPackageRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":     step.Scenario.GetVar("Zone"),
			"Region":   step.Scenario.GetVar("Region"),
			"BackupId": step.Must(functions.SearchValue(step.Scenario.GetVar("DataSet_package1"), "BackupName", "auto_binlog_package", "BackupId")),
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DeleteUDBLogPackage(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
		}
	},
	StartupDelay:  time.Duration(80) * time.Second,
	MaxRetries:    3,
	RetryInterval: 1 * time.Second,
	Title:         "删除UDB日志包",
	FastFail:      false,
}

var testStep491BackupUDBInstanceSlowLog13 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewBackupUDBInstanceSlowLogRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Region":     step.Scenario.GetVar("Region"),
			"EndTime":    step.Must(functions.GetTimestamp(10)),
			"DBId":       step.Scenario.GetVar("DBId"),
			"BeginTime":  step.Must(functions.Calculate("-", step.Must(functions.GetTimestamp(10)), step.Must(functions.Calculate("*", 86400, 7)))),
			"BackupName": "auto_slowlog_package",
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.BackupUDBInstanceSlowLog(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
		}
	},
	StartupDelay:  time.Duration(1) * time.Second,
	MaxRetries:    0,
	RetryInterval: 0 * time.Second,
	Title:         "备份UDB指定时间段的slowlog分析结果",
	FastFail:      false,
}

var testStep491DescribeUDBLogPackage14 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDescribeUDBLogPackageRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":   step.Scenario.GetVar("Zone"),
			"Type":   3,
			"Region": step.Scenario.GetVar("Region"),
			"Offset": 0,
			"Limit":  100,
			"DBId":   step.Scenario.GetVar("DBId"),
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DescribeUDBLogPackage(req)
		if err != nil {
			return resp, err
		}

		step.Scenario.SetVar("DataSet_package2", step.Must(utils.GetValue(resp, "DataSet")))
		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
			validation.Builtins.NewValidator("Action", "DescribeUDBLogPackageResponse", "str_eq"),
			validation.Builtins.NewValidator("DataSet.0.State", "Success", "str_eq"),
		}
	},
	StartupDelay:  time.Duration(150) * time.Second,
	MaxRetries:    3,
	RetryInterval: 1 * time.Second,
	Title:         "列表UDB实例日志备份信息",
	FastFail:      true,
}

var testStep491DescribeUDBLogBackupURL15 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDescribeUDBLogBackupURLRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":     step.Scenario.GetVar("Zone"),
			"Region":   step.Scenario.GetVar("Region"),
			"DBId":     step.Scenario.GetVar("DBId"),
			"BackupId": step.Scenario.GetVar("BackupId"),
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DescribeUDBLogBackupURL(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
			validation.Builtins.NewValidator("Action", "DescribeUDBLogBackupURLResponse", "str_eq"),
		}
	},
	StartupDelay:  time.Duration(0) * time.Second,
	MaxRetries:    3,
	RetryInterval: 1 * time.Second,
	Title:         "获取UDB的slowlog备份地址",
	FastFail:      false,
}

var testStep491DescribeUDBInstanceLog16 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDescribeUDBInstanceLogRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":      step.Scenario.GetVar("Zone"),
			"Region":    step.Scenario.GetVar("Region"),
			"LogType":   "slow",
			"EndTime":   step.Must(functions.GetTimestamp(10)),
			"DBId":      step.Scenario.GetVar("DBId"),
			"BeginTime": step.Must(functions.Calculate("-", step.Must(functions.GetTimestamp(10)), 86400)),
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DescribeUDBInstanceLog(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
			validation.Builtins.NewValidator("Action", "DescribeUDBInstanceLogResponse", "str_eq"),
		}
	},
	StartupDelay:  time.Duration(0) * time.Second,
	MaxRetries:    3,
	RetryInterval: 1 * time.Second,
	Title:         "获取UDB错误日志或慢查询日志",
	FastFail:      false,
}

var testStep491DeleteUDBLogPackage17 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDeleteUDBLogPackageRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":     step.Scenario.GetVar("Zone"),
			"Region":   step.Scenario.GetVar("Region"),
			"BackupId": step.Must(functions.SearchValue(step.Scenario.GetVar("DataSet_package2"), "BackupName", "auto_slowlog_package", "BackupId")),
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DeleteUDBLogPackage(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
		}
	},
	StartupDelay:  time.Duration(1) * time.Second,
	MaxRetries:    0,
	RetryInterval: 0 * time.Second,
	Title:         "删除UDB日志包",
	FastFail:      false,
}

var testStep491BackupUDBInstanceErrorLog18 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewBackupUDBInstanceErrorLogRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":       step.Scenario.GetVar("Zone"),
			"Region":     step.Scenario.GetVar("Region"),
			"DBId":       step.Scenario.GetVar("DBId"),
			"BackupName": "auto_errorlog_package",
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.BackupUDBInstanceErrorLog(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
		}
	},
	StartupDelay:  time.Duration(1) * time.Second,
	MaxRetries:    0,
	RetryInterval: 0 * time.Second,
	Title:         "备份UDB指定时间段的errorlog",
	FastFail:      false,
}

var testStep491DescribeUDBLogPackage19 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDescribeUDBLogPackageRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":   step.Scenario.GetVar("Zone"),
			"Type":   4,
			"Region": step.Scenario.GetVar("Region"),
			"Offset": 0,
			"Limit":  100,
			"DBId":   step.Scenario.GetVar("DBId"),
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DescribeUDBLogPackage(req)
		if err != nil {
			return resp, err
		}

		step.Scenario.SetVar("DataSet_package3", step.Must(utils.GetValue(resp, "DataSet")))
		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
			validation.Builtins.NewValidator("Action", "DescribeUDBLogPackageResponse", "str_eq"),
			validation.Builtins.NewValidator("DataSet.0.State", "Success", "str_eq"),
		}
	},
	StartupDelay:  time.Duration(150) * time.Second,
	MaxRetries:    3,
	RetryInterval: 1 * time.Second,
	Title:         "列表UDB实例日志备份信息",
	FastFail:      true,
}

var testStep491DescribeUDBBinlogBackupURL20 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDescribeUDBBinlogBackupURLRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":     step.Scenario.GetVar("Zone"),
			"Region":   step.Scenario.GetVar("Region"),
			"DBId":     step.Scenario.GetVar("DBId"),
			"BackupId": step.Must(functions.SearchValue(step.Scenario.GetVar("DataSet_package3"), "BackupName", "auto_errorlog_package", "BackupId")),
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DescribeUDBBinlogBackupURL(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
		}
	},
	StartupDelay:  time.Duration(1) * time.Second,
	MaxRetries:    0,
	RetryInterval: 0 * time.Second,
	Title:         "获取UDB的Binlog备份地址",
	FastFail:      false,
}

var testStep491DescribeUDBInstanceLog21 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDescribeUDBInstanceLogRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":      step.Scenario.GetVar("Zone"),
			"Region":    step.Scenario.GetVar("Region"),
			"LogType":   "error",
			"EndTime":   step.Must(functions.GetTimestamp(10)),
			"DBId":      step.Scenario.GetVar("DBId"),
			"BeginTime": step.Must(functions.Calculate("-", step.Must(functions.GetTimestamp(10)), 86400)),
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DescribeUDBInstanceLog(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
			validation.Builtins.NewValidator("Action", "DescribeUDBInstanceLogResponse", "str_eq"),
		}
	},
	StartupDelay:  time.Duration(0) * time.Second,
	MaxRetries:    3,
	RetryInterval: 1 * time.Second,
	Title:         "获取UDB错误日志或慢查询日志",
	FastFail:      false,
}

var testStep491DeleteUDBLogPackage22 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDeleteUDBLogPackageRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":     step.Scenario.GetVar("Zone"),
			"Region":   step.Scenario.GetVar("Region"),
			"BackupId": step.Must(functions.SearchValue(step.Scenario.GetVar("DataSet_package3"), "BackupName", "auto_errorlog_package", "BackupId")),
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DeleteUDBLogPackage(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
		}
	},
	StartupDelay:  time.Duration(1) * time.Second,
	MaxRetries:    0,
	RetryInterval: 0 * time.Second,
	Title:         "删除UDB日志包",
	FastFail:      false,
}

var testStep491ClearUDBLog23 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewClearUDBLogRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":    step.Scenario.GetVar("Zone"),
			"Region":  step.Scenario.GetVar("Region"),
			"LogType": 30,
			"DBId":    step.Scenario.GetVar("DBId"),
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.ClearUDBLog(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
		}
	},
	StartupDelay:  time.Duration(1) * time.Second,
	MaxRetries:    3,
	RetryInterval: 1 * time.Second,
	Title:         "清除日志",
	FastFail:      false,
}

var testStep491StopUDBInstance24 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewStopUDBInstanceRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":   step.Scenario.GetVar("Zone"),
			"Region": step.Scenario.GetVar("Region"),
			"DBId":   step.Scenario.GetVar("DBId"),
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.StopUDBInstance(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
			validation.Builtins.NewValidator("Action", "StopUDBInstanceResponse", "str_eq"),
		}
	},
	StartupDelay:  time.Duration(0) * time.Second,
	MaxRetries:    3,
	RetryInterval: 1 * time.Second,
	Title:         "关闭云数据库",
	FastFail:      false,
}

var testStep491DescribeUDBInstance25 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDescribeUDBInstanceRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":      step.Scenario.GetVar("Zone"),
			"Region":    step.Scenario.GetVar("Region"),
			"Offset":    0,
			"Limit":     100,
			"DBId":      step.Scenario.GetVar("DBId"),
			"ClassType": "sql",
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DescribeUDBInstance(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{
			validation.Builtins.NewValidator("RetCode", 0, "str_eq"),
			validation.Builtins.NewValidator("DataSet.0.DBTypeId", step.Scenario.GetVar("DBTypeId"), "str_eq"),
			validation.Builtins.NewValidator("DataSet.0.State", "Shutoff", "str_eq"),
		}
	},
	StartupDelay:  time.Duration(0) * time.Second,
	MaxRetries:    20,
	RetryInterval: 3 * time.Second,
	Title:         "获取云数据库信息",
	FastFail:      false,
}

var testStep491DeleteUDBInstance26 = &driver.Step{
	Invoker: func(step *driver.Step) (interface{}, error) {
		c, err := step.LoadFixture("UDB")
		if err != nil {
			return nil, err
		}
		client := c.(*udb.UDBClient)

		req := client.NewDeleteUDBInstanceRequest()
		err = utils.SetRequest(req, map[string]interface{}{
			"Zone":   step.Scenario.GetVar("Zone"),
			"Region": step.Scenario.GetVar("Region"),
			"DBId":   step.Scenario.GetVar("DBId"),
		})
		if err != nil {
			return nil, err
		}

		resp, err := client.DeleteUDBInstance(req)
		if err != nil {
			return resp, err
		}

		return resp, nil
	},
	Validators: func(step *driver.Step) []driver.TestValidator {
		return []driver.TestValidator{}
	},
	StartupDelay:  time.Duration(10) * time.Second,
	MaxRetries:    0,
	RetryInterval: 0 * time.Second,
	Title:         "删除云数据库",
	FastFail:      false,
}
