//Code is generated by ucloud code generator, don't modify it by hand, it will cause undefined behaviors.
//go:generate ucloud-gen-go-api UHost GetUImagePrice

package uhost

import (
	"github.com/ucloud/ucloud-sdk-go/ucloud/request"
	"github.com/ucloud/ucloud-sdk-go/ucloud/response"
)

// GetUImagePriceRequest is request schema for GetUImagePrice action
type GetUImagePriceRequest struct {
	request.CommonBase

	// 镜像Id
	ImageId *string `required:"true"`

	// 购买个数，范围[1,5]
	Count *int `required:"true"`

	// 计费类型。Year，Month，Dynamic，默认返回全部计费方式对应的价格
	ChargeType *string `required:"false"`

	// 购买时长, 默认为1
	Quantity *int `required:"false"`
}

// GetUImagePriceResponse is response schema for GetUImagePrice action
type GetUImagePriceResponse struct {
	response.CommonBase

	// 价格列表 UHostPriceSet
	PriceSet []UHostPriceSet
}

// NewGetUImagePriceRequest will create request of GetUImagePrice action.
func (c *UHostClient) NewGetUImagePriceRequest() *GetUImagePriceRequest {
	req := &GetUImagePriceRequest{}
	c.Client.SetupRequest(req)
	return req
}

// GetUImagePrice - 获取镜像价格
func (c *UHostClient) GetUImagePrice(req *GetUImagePriceRequest) (*GetUImagePriceResponse, error) {
	var err error
	var res GetUImagePriceResponse

	err = c.Client.InvokeAction("GetUImagePrice", req, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}
