// Code is generated by ucloud-model, DO NOT EDIT IT.

package iam

import (
	"github.com/ucloud/ucloud-sdk-go/ucloud"
	"github.com/ucloud/ucloud-sdk-go/ucloud/auth"
)

// IAMClient is the client of IAM
type IAMClient struct {
	*ucloud.Client
}

// NewClient will return a instance of IAMClient
func NewClient(config *ucloud.Config, credential *auth.Credential) *IAMClient {
	meta := ucloud.ClientMeta{Product: "IAM"}
	client := ucloud.NewClientWithMeta(config, credential, meta)
	return &IAMClient{
		client,
	}
}
