// Code is generated by ucloud-model, DO NOT EDIT IT.

package uads

/*
DomainConfigResult - 域名配置结果
*/
type DomainConfigResult struct {

	// 错误码
	Code int

	// 域名
	Domain string

	// 提示信息
	Message string
}

/*
ResourceInfo - 资源信息
*/
type ResourceInfo struct {

	// 资源id
	ResourceId string
}

/*
GameIpInfoTotal - 高防ip信息统一描述结构
*/
type GameIpInfoTotal struct {

	// 高防IP Cname
	Cname string

	// 高防IP
	DefenceIP string

	// 线路类型
	LineType string

	// 用户mark
	Remark string

	// 规则的个数
	RuleCnt int

	// 回源ip列表
	SrcIP []string

	// ip配置状态
	Status string
}

/*
NetStatEntry - 统计条目
*/
type NetStatEntry struct {

	// 流量，单位：Mbits
	Bps float64

	// 包量，单位：pps
	Pps int
}

/*
NetStats - 网络统计
*/
type NetStats struct {

	// 丢弃NetStatEntry
	Drop NetStatEntry

	// 出向NetStatEntry
	Egress NetStatEntry

	// 入向NetStatEntry
	Ingress NetStatEntry

	// Unix时间戳
	Time int
}

/*
ServiceInfo - 高防服务信息
*/
type ServiceInfo struct {

	// 接入模式，Domain：网站接入、IP：非网站接入
	AccessMode string

	// 防护机房所在区域
	AreaLine string

	// 是否开启自动续费
	AutoRenew string

	// 付费类型
	ChargeType string

	// 创建时间
	CreateTime int

	// 套餐基础防护组
	DefenceDDosBaseFlowArr []int

	// 套餐最大防护组
	DefenceDDosMaxFlowArr []int

	// 防护状态，Started：正常、Stopped：关闭、Expired：过期
	DefenceStatus string

	// 防护类型
	DefenceType string

	// 防护机房名称
	EngineRoom []string

	// 过期时间
	ExpiredTime int

	// 转发类型，Proxy：代理、Passthrough：直连
	ForwardType string

	// 套餐ID
	GameId int

	// 线路类型
	LineType string

	// 套餐名称
	Name string

	// 高防类型，1：内地高防、2：海外高防
	NapType int

	// 项目ID
	ProjectId string

	// region id
	RegionId int

	// 资源ID
	ResourceId string

	// 业务带宽
	SrcBandwidth int

	// 供应商ID
	Vendor int
}

/*
EIPAddrSet - EIP地址信息
*/
type EIPAddrSet struct {

	// IP类型：gaofang
	EIPType string

	// 弹性IP地址
	IP string

	// 运营商信息, 枚举值为:  BGP: BGP; International: 国际.
	OperatorName string
}

/*
Resouce - 资源信息
*/
type Resouce struct {

	// EIP资源ID
	EIPId string

	// 资源ID
	ResourceId string

	// 资源名
	ResourceName string

	// 资源类型
	ResourceType string

	// 地区
	Zone string
}

/*
IPInfo - 高防IP信息
*/
type IPInfo struct {

	// 创建时间
	CreateTime int

	// 高防IP信息
	EIPAddr []EIPAddrSet

	// EIP资源ID
	EIPId string

	// EIP Region
	EIPRegion string

	// 资源信息
	Resource Resouce

	// 状态
	Status string

	// 业务组
	Tag string
}

/*
FwdSourceInfoConf - 转发规则，回源信息配置详细结构
*/
type FwdSourceInfoConf struct {

	// 源站IP列表
	IPList []string

	// 源站端口
	Port int

	// 源站，兼容IP和域名
	Source string

	// 源站Toa
	Toa int
}

/*
FwdSourceInfo - 转发规则，回源配置信息
*/
type FwdSourceInfo struct {

	// 回源配置列表
	Conf []FwdSourceInfoConf

	// 回源类型，分 IP 和 Domain
	Type string
}

/*
FwdClientProxyInfo - 转发规则，回源代理配置列表
*/
type FwdClientProxyInfo struct {

	// 回源IP个数
	Count int

	// 回源IP列表
	IPList []string
}

/*
BGPFwdRule - BGP高防的转发规则信息
*/
type BGPFwdRule struct {

	// 备份源站的IP
	BackupIP string

	// 备份源站的端口
	BackupPort int

	// 转发规则对应的BGP高防的IP
	BgpIP string

	// 默认为0，为IP协议的转发端口，其余的自定义，在0~65535范围内即可,但是同一IP下配置的规则端口不能重复
	BgpIPPort int

	// 回源IP结构
	ClientProxyInfo FwdClientProxyInfo

	// 创建时间，unix格式
	CreateTime int

	// 配置的规则的转发类型
	FwdType string

	// 转发协议的类型是否为负载均衡的：默认为“No”，还可以选择为“Yes”。负载模式的规则最多添加2条，非负载模式的规则最多添加8条
	LoadBalance string

	// 备注
	Remark string

	// 转发规则的ID
	RuleID string

	// 生成的规则的数据库索引值
	RuleIndex int

	// 表示对源站进行检测：默认为0表示关闭，还可以选择为1表示开启
	SourceDetect int

	// 源站信息结构
	SourceInfo FwdSourceInfo

	// 规则的状态
	Status string

	// 更新时间，unix格式
	UpdateTime int
}

/*
BlockAllowDomainEntry - 阻止/允许域名条目
*/
type BlockAllowDomainEntry struct {

	// 创建时间戳，例如：1581991500
	CreateTime int

	// 域名
	Domain string

	// 备注
	Remark string

	// 状态；1：添加中，2：成功，3：删除中，4：失败，5：已删除
	Status int
}

/*
NapServiceConfigEntry - 高防服务配置条目
*/
type NapServiceConfigEntry struct {

	// 线路区域
	AreaLine string

	// 灾备配置
	DR string

	// 按天购买配置
	DayPay string

	// 域名配置
	Domain string

	// 是否可以配置域名回源
	DomainSrc string

	// 按需购买配置
	DynamicPay string

	// 购买的套餐所在机房
	EngineRoom string

	// 线路类型
	LineType string

	// 按月购买配置
	MonthPay string

	// 高防类型，1：内地高防、2：海外高防
	NapType int

	// 按年购买配置
	YearPay string
}
