// Code is generated by ucloud-model, DO NOT EDIT IT.

package ucloudstack

import (
	"github.com/ucloud/ucloud-sdk-go/ucloud/request"
	"github.com/ucloud/ucloud-sdk-go/ucloud/response"
)

// ReleaseEIPRequest is request schema for ReleaseEIP action
type ReleaseEIPRequest struct {
	request.CommonBase

	// [公共参数] 地域。枚举值：cn,表示中国；中国
	// Region *string `required:"true"`

	// [公共参数] 可用区。枚举值：zone-01，表示中国
	// Zone *string `required:"true"`

	// 外网IP的ID
	EIPID *string `required:"true"`
}

// ReleaseEIPResponse is response schema for ReleaseEIP action
type ReleaseEIPResponse struct {
	response.CommonBase

	// 返回状态描述
	Message string
}

// NewReleaseEIPRequest will create request of ReleaseEIP action.
func (c *UCloudStackClient) NewReleaseEIPRequest() *ReleaseEIPRequest {
	req := &ReleaseEIPRequest{}

	// setup request with client config
	c.Client.SetupRequest(req)

	// setup retryable with default retry policy (retry for non-create action and common error)
	req.SetRetryable(true)
	return req
}

// ReleaseEIP - 删除外网IP
func (c *UCloudStackClient) ReleaseEIP(req *ReleaseEIPRequest) (*ReleaseEIPResponse, error) {
	var err error
	var res ReleaseEIPResponse

	reqCopier := *req

	err = c.Client.InvokeAction("ReleaseEIP", &reqCopier, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}
