// Code is generated by ucloud-model, DO NOT EDIT IT.

package ucloudstack

/*
VMInstanceInfo - UCloudStack虚拟机信息

this model is auto created by ucloud code generater for open api,
you can also see https://docs.ucloud.cn/api for detail.
*/
type VMInstanceInfo struct {

	// CPU 个数
	CPU int

	// 虚拟机计费模式。枚举值：Dynamic，表示小时；Month，表示月；Year，表示年；
	ChargeType string

	// 虚拟机创建时间
	CreateTime int

	// 磁盘信息
	DiskInfos []VMDiskInfo

	// 虚拟机过期时间
	ExpireTime int

	// IP 信息
	IPInfos []VMIPInfo

	// 镜像 ID
	ImageID string

	// 内存大小，单位 M
	Memory int

	// 虚拟机名称
	Name string

	// 操作系统名称
	OSName string

	// 操作系统类型
	OSType string

	// Region
	Region string

	// Region 别名
	RegionAlias string

	// 备注
	Remark string

	// 虚拟机状态。枚举值：Initializing，表示初始化；Starting，表示启动中；Restarting，表示重启中；Running，表示运行；Stopping，表示关机中；Stopped，表示关机；Deleted，表示已删除；Resizing，表示修改配置中；Terminating，表示销毁中；Terminated，表示已销毁；Migrating，表示迁移中；WaitReinstall，表示重装中；Reinstalling，表示重装中；Poweroffing，表示断电中；ChangeSGing，表示修改防火墙中；
	State string

	// 子网 ID
	SubnetID string

	// 子网 名称
	SubnetName string

	// 虚拟机 ID
	VMID string

	// 虚拟机类型
	VMType string

	// 虚拟机类型别名
	VMTypeAlias string

	// VPC ID
	VPCID string

	// VPC 名称
	VPCName string

	// Zone
	Zone string

	// Zone 别名
	ZoneAlias string
}
