// Code is generated by ucloud-model, DO NOT EDIT IT.

package ucloudstack

/*
VMIPInfo - UCloudStack虚拟机IP信息

this model is auto created by ucloud code generater for open api,
you can also see https://docs.ucloud.cn/api for detail.
*/
type VMIPInfo struct {

	// IP 值
	IP string

	// 网卡 ID
	InterfaceID string

	// 是否是弹性网卡。枚举值：Y，表示是；N，表示否；
	IsElastic string

	// MAC 地址值
	MAC string

	// 安全组 ID
	SGID string

	// 安全组名称
	SGName string

	// 子网 ID
	SubnetID string

	// 子网名称
	SubnetName string

	// IP 类型。枚举值：Private，表示内网；Public，表示外网；Physical，表示物理网；
	Type string

	// VPC ID
	VPCID string

	// VPC 名称
	VPCName string
}
