// Code is generated by ucloud-model, DO NOT EDIT IT.

package ipsecvpn

import (
	"github.com/ucloud/ucloud-sdk-go/ucloud/request"
	"github.com/ucloud/ucloud-sdk-go/ucloud/response"
)

// GetVPNGatewayUpgradePriceRequest is request schema for GetVPNGatewayUpgradePrice action
type GetVPNGatewayUpgradePriceRequest struct {
	request.CommonBase

	// [公共参数] 项目ID。不填写为默认项目，子帐号必须填写。 请参考[GetProjectList接口](../summary/get_project_list.html)
	// ProjectId *string `required:"true"`

	// [公共参数] 地域。 参见 [地域和可用区列表](../summary/regionlist.html)
	// Region *string `required:"true"`

	// 更改的VPN网关规格，枚举值为: Standard, 标准型; Enhanced, 增强型。
	Grade *string `required:"true"`

	// VPN网关的资源ID
	VPNGatewayId *string `required:"true"`
}

// GetVPNGatewayUpgradePriceResponse is response schema for GetVPNGatewayUpgradePrice action
type GetVPNGatewayUpgradePriceResponse struct {
	response.CommonBase

	// 调整规格后的VPN网关价格, 单位为"元", 如需退费此处为负值
	Price float64
}

// NewGetVPNGatewayUpgradePriceRequest will create request of GetVPNGatewayUpgradePrice action.
func (c *IPSecVPNClient) NewGetVPNGatewayUpgradePriceRequest() *GetVPNGatewayUpgradePriceRequest {
	req := &GetVPNGatewayUpgradePriceRequest{}

	// setup request with client config
	c.Client.SetupRequest(req)

	// setup retryable with default retry policy (retry for non-create action and common error)
	req.SetRetryable(true)
	return req
}

// GetVPNGatewayUpgradePrice - 获取VPN网关规格改动价格
func (c *IPSecVPNClient) GetVPNGatewayUpgradePrice(req *GetVPNGatewayUpgradePriceRequest) (*GetVPNGatewayUpgradePriceResponse, error) {
	var err error
	var res GetVPNGatewayUpgradePriceResponse

	reqCopier := *req

	err = c.Client.InvokeAction("GetVPNGatewayUpgradePrice", &reqCopier, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}
