#!/bin/sh
set -e

ARGS=$@
if [ -z "$ARGS" ]; then
    ARGS="./..."
fi

echo $ARGS

docker build -t goucloud .
exec docker run --rm \
                -v `pwd`:/go/src/github.com/ucloud/ucloud-sdk-go \
                goucloud godep go build $ARGS
