// Code is generated by ucloud-model, DO NOT EDIT IT.

/*
Package upgsql include resources of ucloud upgsql product

See also

  - API: https://docs.ucloud.cn/api/upgsql-api/index
  - Product: https://www.ucloud.cn/site/product/upgsql.html

for detail.
*/
package upgsql
