// Code is generated by ucloud-model, DO NOT EDIT IT.

package usnap

import (
	"github.com/ucloud/ucloud-sdk-go/ucloud/request"
	"github.com/ucloud/ucloud-sdk-go/ucloud/response"
)

// USnap API Schema

// CreateSnapshotServiceRequest is request schema for CreateSnapshotService action
type CreateSnapshotServiceRequest struct {
	request.CommonBase

	// [公共参数] 项目ID。不填写为默认项目，子帐号必须填写。 请参考[GetProjectList接口](https://docs.ucloud.cn/api/summary/get_project_list)
	// ProjectId *string `required:"false"`

	// [公共参数] 地域。 参见 [地域和可用区列表](https://docs.ucloud.cn/api/summary/regionlist)
	// Region *string `required:"true"`

	// [公共参数] 可用区。参见 [可用区列表](https://docs.ucloud.cn/api/summary/regionlist)
	// Zone *string `required:"true"`

	// 默认采用基础版套餐开通，“Base”：基础版，“ Ultimate”：旗舰版，“ Custom”：自定义备份链
	BackupMode *string `required:"false"`

	// Year , Month, Dynamic 默认: Month
	ChargeType *string `required:"false"`

	// 代金券ID
	CouponId *string `required:"false"`

	// BackupMode为Custom时，进行设置, 以5天级为基础进行倍数扩增，如5、10、15、20、25、30
	Day *int `required:"false"`

	// BackupMode为Custom时，进行设置, 以24小时级为基础进行倍数扩增，如24、48、72、96
	Hour *int `required:"false"`

	// BackupMode为Custom时，进行设置, 以12小时秒级为基础进行倍数扩增，如12、24、36、48
	Journal *int `required:"false"`

	// 购买时长 默认: 1
	Quantity *int `required:"false"`

	// 业务组 默认：Default
	Tag *string `required:"false"`

	// 磁盘ID
	VDiskId *string `required:"true"`
}

// CreateSnapshotServiceResponse is response schema for CreateSnapshotService action
type CreateSnapshotServiceResponse struct {
	response.CommonBase

	// 快照服务ID
	SnapshotServiceId string

	// 快照服务状态,状态:Available(可用),InAvailable(不可用),Expired(欠费)
	Status string
}

// NewCreateSnapshotServiceRequest will create request of CreateSnapshotService action.
func (c *USnapClient) NewCreateSnapshotServiceRequest() *CreateSnapshotServiceRequest {
	req := &CreateSnapshotServiceRequest{}

	// setup request with client config
	c.Client.SetupRequest(req)

	// setup retryable with default retry policy (retry for non-create action and common error)
	req.SetRetryable(false)
	return req
}

/*
API: CreateSnapshotService

创建磁盘快照服务
*/
func (c *USnapClient) CreateSnapshotService(req *CreateSnapshotServiceRequest) (*CreateSnapshotServiceResponse, error) {
	var err error
	var res CreateSnapshotServiceResponse

	reqCopier := *req

	err = c.Client.InvokeAction("CreateSnapshotService", &reqCopier, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}

// CreateUSnapGroupRequest is request schema for CreateUSnapGroup action
type CreateUSnapGroupRequest struct {
	request.CommonBase

	// [公共参数] 项目ID。不填写为默认项目，子帐号必须填写。 请参考[GetProjectList接口](https://docs.ucloud.cn/api/summary/get_project_list)
	// ProjectId *string `required:"false"`

	// [公共参数] 地域。 参见 [地域和可用区列表](https://docs.ucloud.cn/api/summary/regionlist)
	// Region *string `required:"true"`

	// [公共参数] 可用区。参见 [可用区列表](https://docs.ucloud.cn/api/summary/regionlist)
	// Zone *string `required:"true"`

	// 一致性组快照名称
	Name *string `required:"true"`

	// 需要创建一致性组快照的磁盘ID列表
	VDiskIds *string `required:"true"`
}

// CreateUSnapGroupResponse is response schema for CreateUSnapGroup action
type CreateUSnapGroupResponse struct {
	response.CommonBase

	// 创建快照失败数量
	FailCount int

	// 创建快照失败磁盘列表
	FailList []string

	// 一致性组ID
	GroupId string
}

// NewCreateUSnapGroupRequest will create request of CreateUSnapGroup action.
func (c *USnapClient) NewCreateUSnapGroupRequest() *CreateUSnapGroupRequest {
	req := &CreateUSnapGroupRequest{}

	// setup request with client config
	c.Client.SetupRequest(req)

	// setup retryable with default retry policy (retry for non-create action and common error)
	req.SetRetryable(false)
	return req
}

/*
API: CreateUSnapGroup

创建快照一致性组
*/
func (c *USnapClient) CreateUSnapGroup(req *CreateUSnapGroupRequest) (*CreateUSnapGroupResponse, error) {
	var err error
	var res CreateUSnapGroupResponse

	reqCopier := *req

	err = c.Client.InvokeAction("CreateUSnapGroup", &reqCopier, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}

// DeleteSnapshotServiceRequest is request schema for DeleteSnapshotService action
type DeleteSnapshotServiceRequest struct {
	request.CommonBase

	// [公共参数] 项目ID。不填写为默认项目，子帐号必须填写。 请参考[GetProjectList接口](https://docs.ucloud.cn/api/summary/get_project_list)
	// ProjectId *string `required:"false"`

	// [公共参数] 地域。 参见 [地域和可用区列表](https://docs.ucloud.cn/api/summary/regionlist)
	// Region *string `required:"true"`

	// [公共参数] 可用区。参见 [可用区列表](https://docs.ucloud.cn/api/summary/regionlist)
	// Zone *string `required:"true"`

	// 磁盘ID
	VDiskId *string `required:"true"`
}

// DeleteSnapshotServiceResponse is response schema for DeleteSnapshotService action
type DeleteSnapshotServiceResponse struct {
	response.CommonBase
}

// NewDeleteSnapshotServiceRequest will create request of DeleteSnapshotService action.
func (c *USnapClient) NewDeleteSnapshotServiceRequest() *DeleteSnapshotServiceRequest {
	req := &DeleteSnapshotServiceRequest{}

	// setup request with client config
	c.Client.SetupRequest(req)

	// setup retryable with default retry policy (retry for non-create action and common error)
	req.SetRetryable(true)
	return req
}

/*
API: DeleteSnapshotService

删除磁盘快照服务
*/
func (c *USnapClient) DeleteSnapshotService(req *DeleteSnapshotServiceRequest) (*DeleteSnapshotServiceResponse, error) {
	var err error
	var res DeleteSnapshotServiceResponse

	reqCopier := *req

	err = c.Client.InvokeAction("DeleteSnapshotService", &reqCopier, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}

// DeleteUSnapGroupRequest is request schema for DeleteUSnapGroup action
type DeleteUSnapGroupRequest struct {
	request.CommonBase

	// [公共参数] 项目ID。不填写为默认项目，子帐号必须填写。 请参考[GetProjectList接口](https://docs.ucloud.cn/api/summary/get_project_list)
	// ProjectId *string `required:"false"`

	// [公共参数] 地域。 参见 [地域和可用区列表](https://docs.ucloud.cn/api/summary/regionlist)
	// Region *string `required:"true"`

	// [公共参数] 可用区。参见 [可用区列表](https://docs.ucloud.cn/api/summary/regionlist)
	// Zone *string `required:"true"`

	// 一致性组ID
	GroupId *string `required:"true"`
}

// DeleteUSnapGroupResponse is response schema for DeleteUSnapGroup action
type DeleteUSnapGroupResponse struct {
	response.CommonBase
}

// NewDeleteUSnapGroupRequest will create request of DeleteUSnapGroup action.
func (c *USnapClient) NewDeleteUSnapGroupRequest() *DeleteUSnapGroupRequest {
	req := &DeleteUSnapGroupRequest{}

	// setup request with client config
	c.Client.SetupRequest(req)

	// setup retryable with default retry policy (retry for non-create action and common error)
	req.SetRetryable(true)
	return req
}

/*
API: DeleteUSnapGroup

删除快照一致性组
*/
func (c *USnapClient) DeleteUSnapGroup(req *DeleteUSnapGroupRequest) (*DeleteUSnapGroupResponse, error) {
	var err error
	var res DeleteUSnapGroupResponse

	reqCopier := *req

	err = c.Client.InvokeAction("DeleteUSnapGroup", &reqCopier, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}

// DescribeSnapshotServiceRequest is request schema for DescribeSnapshotService action
type DescribeSnapshotServiceRequest struct {
	request.CommonBase

	// [公共参数] 项目ID。不填写为默认项目，子帐号必须填写。 请参考[GetProjectList接口](https://docs.ucloud.cn/api/summary/get_project_list)
	// ProjectId *string `required:"false"`

	// [公共参数] 地域。 参见 [地域和可用区列表](https://docs.ucloud.cn/api/summary/regionlist)
	// Region *string `required:"true"`

	// [公共参数] 可用区。参见 [可用区列表](https://docs.ucloud.cn/api/summary/regionlist)
	// Zone *string `required:"true"`

	// 返回数据长度, 默认为20
	Limit *int `required:"false"`

	// 数据偏移量, 默认为0
	Offset *int `required:"false"`

	// 快照ID (传入则获取当前快照对应盘的快照服务, 不传则获取当前可用区快照服务列表，磁盘ID和快照ID同时传入以磁盘ID为准)
	SnapshotId *string `required:"false"`

	// 快照服务ID(传入则获取当前快照服务ID, 不传则获取当前可用区快照服务列表)
	SnapshotServiceId *string `required:"false"`

	// 磁盘ID (传入则获取当前盘快照服务, 不传则获取当前可用区快照服务列表)
	VDiskId *string `required:"false"`
}

// DescribeSnapshotServiceResponse is response schema for DescribeSnapshotService action
type DescribeSnapshotServiceResponse struct {
	response.CommonBase

	// 快照服务列表
	DataSet []SnapshotServiceDataSet

	// 快照服务DataSet总数
	TotalCount int
}

// NewDescribeSnapshotServiceRequest will create request of DescribeSnapshotService action.
func (c *USnapClient) NewDescribeSnapshotServiceRequest() *DescribeSnapshotServiceRequest {
	req := &DescribeSnapshotServiceRequest{}

	// setup request with client config
	c.Client.SetupRequest(req)

	// setup retryable with default retry policy (retry for non-create action and common error)
	req.SetRetryable(true)
	return req
}

/*
API: DescribeSnapshotService

获取磁盘快照服务列表
*/
func (c *USnapClient) DescribeSnapshotService(req *DescribeSnapshotServiceRequest) (*DescribeSnapshotServiceResponse, error) {
	var err error
	var res DescribeSnapshotServiceResponse

	reqCopier := *req

	err = c.Client.InvokeAction("DescribeSnapshotService", &reqCopier, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}

// DescribeSnapshotServicePriceRequest is request schema for DescribeSnapshotServicePrice action
type DescribeSnapshotServicePriceRequest struct {
	request.CommonBase

	// [公共参数] 项目ID。不填写为默认项目，子帐号必须填写。 请参考[GetProjectList接口](https://docs.ucloud.cn/api/summary/get_project_list)
	// ProjectId *string `required:"false"`

	// [公共参数] 地域。 参见 [地域和可用区列表](https://docs.ucloud.cn/api/summary/regionlist)
	// Region *string `required:"true"`

	// [公共参数] 可用区。参见 [可用区列表](https://docs.ucloud.cn/api/summary/regionlist)
	// Zone *string `required:"true"`

	// 默认采用基础版套餐开通，“Base”：基础版，“ Ultimate”：旗舰版，“ Custom”：自定义备份链
	BackupMode *string `required:"false"`

	// Year , Month, Dynamic 默认: Month
	ChargeType *string `required:"false"`

	// BackupMode为Custom时，进行设置, 以5天级为基础进行倍数扩增，如5、10、15、20、25、30
	Day *int `required:"false"`

	// BackupMode为Custom时，进行设置, 以24小时级为基础进行倍数扩增，如24、48、72、96
	Hour *int `required:"false"`

	// BackupMode为Custom时，进行设置, 以12小时秒级为基础进行倍数扩增，如12、24、36、48
	Journal *int `required:"false"`

	// 购买服务时长，默认值是1
	Quantity *int `required:"false"`

	// 磁盘大小
	Size *int `required:"true"`
}

// DescribeSnapshotServicePriceResponse is response schema for DescribeSnapshotServicePrice action
type DescribeSnapshotServicePriceResponse struct {
	response.CommonBase

	// 价格参数列表，具体说明见SnapshotServicePriceDataSet
	DataSet SnapshotServicePriceDataSet
}

// NewDescribeSnapshotServicePriceRequest will create request of DescribeSnapshotServicePrice action.
func (c *USnapClient) NewDescribeSnapshotServicePriceRequest() *DescribeSnapshotServicePriceRequest {
	req := &DescribeSnapshotServicePriceRequest{}

	// setup request with client config
	c.Client.SetupRequest(req)

	// setup retryable with default retry policy (retry for non-create action and common error)
	req.SetRetryable(true)
	return req
}

/*
API: DescribeSnapshotServicePrice

获取磁盘快照服务实例价格信息
*/
func (c *USnapClient) DescribeSnapshotServicePrice(req *DescribeSnapshotServicePriceRequest) (*DescribeSnapshotServicePriceResponse, error) {
	var err error
	var res DescribeSnapshotServicePriceResponse

	reqCopier := *req

	err = c.Client.InvokeAction("DescribeSnapshotServicePrice", &reqCopier, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}

// DescribeSnapshotServiceUpgradePriceRequest is request schema for DescribeSnapshotServiceUpgradePrice action
type DescribeSnapshotServiceUpgradePriceRequest struct {
	request.CommonBase

	// [公共参数] 项目ID。不填写为默认项目，子帐号必须填写。 请参考[GetProjectList接口](https://docs.ucloud.cn/api/summary/get_project_list)
	// ProjectId *string `required:"false"`

	// [公共参数] 地域。 参见 [地域和可用区列表](https://docs.ucloud.cn/api/summary/regionlist)
	// Region *string `required:"true"`

	// [公共参数] 可用区。参见 [可用区列表](https://docs.ucloud.cn/api/summary/regionlist)
	// Zone *string `required:"true"`

	// 磁盘大小
	Size *int `required:"true"`

	// 升降级快照服务, 升级"Yes",降级"No", 默认为No
	SnapshotsvcMode *string `required:"false"`

	// 磁盘ID
	VDiskId *string `required:"true"`
}

// DescribeSnapshotServiceUpgradePriceResponse is response schema for DescribeSnapshotServiceUpgradePrice action
type DescribeSnapshotServiceUpgradePriceResponse struct {
	response.CommonBase

	// 折扣后价格
	OriginalPrice int

	// 价格
	Price int
}

// NewDescribeSnapshotServiceUpgradePriceRequest will create request of DescribeSnapshotServiceUpgradePrice action.
func (c *USnapClient) NewDescribeSnapshotServiceUpgradePriceRequest() *DescribeSnapshotServiceUpgradePriceRequest {
	req := &DescribeSnapshotServiceUpgradePriceRequest{}

	// setup request with client config
	c.Client.SetupRequest(req)

	// setup retryable with default retry policy (retry for non-create action and common error)
	req.SetRetryable(true)
	return req
}

/*
API: DescribeSnapshotServiceUpgradePrice

获取快照服务升降级价格
*/
func (c *USnapClient) DescribeSnapshotServiceUpgradePrice(req *DescribeSnapshotServiceUpgradePriceRequest) (*DescribeSnapshotServiceUpgradePriceResponse, error) {
	var err error
	var res DescribeSnapshotServiceUpgradePriceResponse

	reqCopier := *req

	err = c.Client.InvokeAction("DescribeSnapshotServiceUpgradePrice", &reqCopier, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}

// DescribeUSnapBackupRangeRequest is request schema for DescribeUSnapBackupRange action
type DescribeUSnapBackupRangeRequest struct {
	request.CommonBase

	// [公共参数] 项目ID。不填写为默认项目，子帐号必须填写。 请参考[GetProjectList接口](https://docs.ucloud.cn/api/summary/get_project_list)
	// ProjectId *string `required:"false"`

	// [公共参数] 地域。 参见 [地域和可用区列表](https://docs.ucloud.cn/api/summary/regionlist)
	// Region *string `required:"true"`

	// [公共参数] 可用区。参见 [可用区列表](https://docs.ucloud.cn/api/summary/regionlist)
	// Zone *string `required:"true"`

	// 磁盘ID
	VDiskId *string `required:"true"`
}

// DescribeUSnapBackupRangeResponse is response schema for DescribeUSnapBackupRange action
type DescribeUSnapBackupRangeResponse struct {
	response.CommonBase

	// “ Primer”：入门版，“Base”：基础版，“ Enterprise”：企业版，“ Ultimate”：旗舰版，“ Custom”：自定义备份链
	BackupMode string

	// 详见BackupRange模型
	BackupRange BackupRange
}

// NewDescribeUSnapBackupRangeRequest will create request of DescribeUSnapBackupRange action.
func (c *USnapClient) NewDescribeUSnapBackupRangeRequest() *DescribeUSnapBackupRangeRequest {
	req := &DescribeUSnapBackupRangeRequest{}

	// setup request with client config
	c.Client.SetupRequest(req)

	// setup retryable with default retry policy (retry for non-create action and common error)
	req.SetRetryable(true)
	return req
}

/*
API: DescribeUSnapBackupRange

查询备份链范围
*/
func (c *USnapClient) DescribeUSnapBackupRange(req *DescribeUSnapBackupRangeRequest) (*DescribeUSnapBackupRangeResponse, error) {
	var err error
	var res DescribeUSnapBackupRangeResponse

	reqCopier := *req

	err = c.Client.InvokeAction("DescribeUSnapBackupRange", &reqCopier, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}

// DescribeUSnapGroupRequest is request schema for DescribeUSnapGroup action
type DescribeUSnapGroupRequest struct {
	request.CommonBase

	// [公共参数] 项目ID。不填写为默认项目，子帐号必须填写。 请参考[GetProjectList接口](https://docs.ucloud.cn/api/summary/get_project_list)
	// ProjectId *string `required:"false"`

	// [公共参数] 地域。 参见 [地域和可用区列表](https://docs.ucloud.cn/api/summary/regionlist)
	// Region *string `required:"true"`

	// [公共参数] 可用区。参见 [可用区列表](https://docs.ucloud.cn/api/summary/regionlist)
	// Zone *string `required:"true"`

	// 一致性组快照ID
	GroupId *string `required:"true"`
}

// DescribeUSnapGroupResponse is response schema for DescribeUSnapGroup action
type DescribeUSnapGroupResponse struct {
	response.CommonBase

	// 快照列表信息
	SnapshotList []SnapInfo
}

// NewDescribeUSnapGroupRequest will create request of DescribeUSnapGroup action.
func (c *USnapClient) NewDescribeUSnapGroupRequest() *DescribeUSnapGroupRequest {
	req := &DescribeUSnapGroupRequest{}

	// setup request with client config
	c.Client.SetupRequest(req)

	// setup retryable with default retry policy (retry for non-create action and common error)
	req.SetRetryable(true)
	return req
}

/*
API: DescribeUSnapGroup

查询快照一致性组详情信息
*/
func (c *USnapClient) DescribeUSnapGroup(req *DescribeUSnapGroupRequest) (*DescribeUSnapGroupResponse, error) {
	var err error
	var res DescribeUSnapGroupResponse

	reqCopier := *req

	err = c.Client.InvokeAction("DescribeUSnapGroup", &reqCopier, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}

// DescribeUSnapGroupListRequest is request schema for DescribeUSnapGroupList action
type DescribeUSnapGroupListRequest struct {
	request.CommonBase

	// [公共参数] 项目ID。不填写为默认项目，子帐号必须填写。 请参考[GetProjectList接口](https://docs.ucloud.cn/api/summary/get_project_list)
	// ProjectId *string `required:"false"`

	// [公共参数] 地域。 参见 [地域和可用区列表](https://docs.ucloud.cn/api/summary/regionlist)
	// Region *string `required:"true"`

	// [公共参数] 可用区。参见 [可用区列表](https://docs.ucloud.cn/api/summary/regionlist)
	// Zone *string `required:"true"`

	// 一致性组快照ID,不填默认拉全量列表
	GroupId *string `required:"false"`
}

// DescribeUSnapGroupListResponse is response schema for DescribeUSnapGroupList action
type DescribeUSnapGroupListResponse struct {
	response.CommonBase

	// 一致性组快照列表信息
	GroupList []SnapGroupInfo

	// 一致性组数量
	TotalCount int
}

// NewDescribeUSnapGroupListRequest will create request of DescribeUSnapGroupList action.
func (c *USnapClient) NewDescribeUSnapGroupListRequest() *DescribeUSnapGroupListRequest {
	req := &DescribeUSnapGroupListRequest{}

	// setup request with client config
	c.Client.SetupRequest(req)

	// setup retryable with default retry policy (retry for non-create action and common error)
	req.SetRetryable(true)
	return req
}

/*
API: DescribeUSnapGroupList

查询快照一致性组
*/
func (c *USnapClient) DescribeUSnapGroupList(req *DescribeUSnapGroupListRequest) (*DescribeUSnapGroupListResponse, error) {
	var err error
	var res DescribeUSnapGroupListResponse

	reqCopier := *req

	err = c.Client.InvokeAction("DescribeUSnapGroupList", &reqCopier, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}

// UpgradeUSnapBackupRangeRequest is request schema for UpgradeUSnapBackupRange action
type UpgradeUSnapBackupRangeRequest struct {
	request.CommonBase

	// [公共参数] 项目ID。不填写为默认项目，子帐号必须填写。 请参考[GetProjectList接口](https://docs.ucloud.cn/api/summary/get_project_list)
	// ProjectId *string `required:"false"`

	// [公共参数] 地域。 参见 [地域和可用区列表](https://docs.ucloud.cn/api/summary/regionlist)
	// Region *string `required:"true"`

	// [公共参数] 可用区。参见 [可用区列表](https://docs.ucloud.cn/api/summary/regionlist)
	// Zone *string `required:"true"`

	// 默认采用入门级套餐开通，“ Primer”：入门版，“Base”：基础版，“ Enterprise”：企业版，“ Ultimate”：旗舰版，“ Custom”：自定义备份链
	BackupMode *int `required:"true"`

	// BackupMode为Custom时，进行设置, 以5天级为基础进行倍数扩增，如5、10、15、20、25、30
	Day *int `required:"false"`

	// BackupMode为Custom时，进行设置, 以24小时级为基础进行倍数扩增，如24、48、72、96
	Hour *int `required:"false"`

	// BackupMode为Custom时，进行设置, 以12小时秒级为基础进行倍数扩增，如12、24、36、48
	Journal *int `required:"false"`

	// 磁盘大小
	Size *int `required:"true"`

	// 快照服务ID
	SnapshotSvcId *string `required:"false"`

	// 磁盘ID
	VDiskId *string `required:"true"`
}

// UpgradeUSnapBackupRangeResponse is response schema for UpgradeUSnapBackupRange action
type UpgradeUSnapBackupRangeResponse struct {
	response.CommonBase
}

// NewUpgradeUSnapBackupRangeRequest will create request of UpgradeUSnapBackupRange action.
func (c *USnapClient) NewUpgradeUSnapBackupRangeRequest() *UpgradeUSnapBackupRangeRequest {
	req := &UpgradeUSnapBackupRangeRequest{}

	// setup request with client config
	c.Client.SetupRequest(req)

	// setup retryable with default retry policy (retry for non-create action and common error)
	req.SetRetryable(true)
	return req
}

/*
API: UpgradeUSnapBackupRange

调整备份链范围
*/
func (c *USnapClient) UpgradeUSnapBackupRange(req *UpgradeUSnapBackupRangeRequest) (*UpgradeUSnapBackupRangeResponse, error) {
	var err error
	var res UpgradeUSnapBackupRangeResponse

	reqCopier := *req

	err = c.Client.InvokeAction("UpgradeUSnapBackupRange", &reqCopier, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}
