// Code is generated by ucloud-model, DO NOT EDIT IT.

package usnap

import (
	"github.com/ucloud/ucloud-sdk-go/ucloud"
	"github.com/ucloud/ucloud-sdk-go/ucloud/auth"
)

// USnapClient is the client of USnap
type USnapClient struct {
	*ucloud.Client
}

// NewClient will return a instance of USnapClient
func NewClient(config *ucloud.Config, credential *auth.Credential) *USnapClient {
	meta := ucloud.ClientMeta{Product: "USnap"}
	client := ucloud.NewClientWithMeta(config, credential, meta)
	return &USnapClient{
		client,
	}
}
